name: Build Base Image
on: 
  workflow_dispatch:
    inputs:
      image: 
        description: image name:tag to sync, ex.  busybox:latest
        required: true
        type: choice
        default: davionlinux
        options:
        - davion-node
        - davion-ubuntu
      targetEcrAccountId: 
        description: target ecr account
        required: true
        default: 148478469270
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Build Image
        run: |
          URL=""https://api.github.com/repos/lq0317/github-actions-test/pulls/12/files""
          response=$(curl -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.v3+json" -s -X GET -G $URL)
          DOCKERFILE_DIR=$(echo "${response}" | jq -r '.[] | .filename'|cut -d "/" -f1-3 |sort |uniq)
          current_dir=$(pwd)
          file=$(echo "${response}" | jq -r '.[] | .filename')
          echo ${file}
          ls
          echo ${DOCKERFILE_DIR}
          pwd
          for i in ${DOCKERFILE_DIR};do
            IMAGE=$(echo $i|cut -d "/" -f2)
            echo $IMAGE
            TAG=$(echo $i|cut -d "/" -f3)
            echo $TAG
            IMAGE_URL=${ECR_REGISTRY}/${IMAGE}:${tag}
            echo ${IMAGE_URL}
            cd ${current_dir}/$i
            ls
            #cmd="docker build -f ${DOCKERFILE_DIR}/Dockerfile -t ${IMAGE_URL} ."
          done
