name: Build Base Image
on: 
  workflow_dispatch:
    inputs:
      image: 
        description: image name:tag to sync, ex.  busybox:latest
        required: true
        type: choice
        default: davionlinux
        options:
        - davion-amazonlinux
        - davion-centos
        - davion-alpine
        - davion-nginx
        - davion-nginxspa
        - davion-openjdk
        - davion-node
        - davion-actions-runner
        - davion-ubuntu
      targetEcrAccountId: 
        description: target ecr account
        required: true
        default: 148478469270
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Build Image
        working-directory: dockerfiles/${{ github.event.inputs.image }}
        run: |
          echo ${working-directory}
          source ../../cicd/libs/bash_color.sh
          for i in */; do
            cd $i
            echo $i
            tag=${i//\//}
            echo $tag
            IMAGE_URL=${ECR_REGISTRY}/${IMAGE}:${tag}
            echo ${IMAGE_URL}
            cd ..
          done
