on:
  pull_request:
    branches:
      - master
    paths:
      - dockerfiles/**
env:
  default_account: 148478469270

jobs:
  build:
    runs-on: [self-hosted, linux, x64, eks, automation-default]
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
        with:
          registries: ${default_account}
      - name: List Changefile
        id: changefile
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          response=$(curl -H 'authorization: Bearer ${{ secrets.Test }}' -H "Accept: application/vnd.github.v3+json" -s -X GET -G $URL)
          FILES=$(echo "${response}" | jq -r '.[] | .filename')     		
          echo ${FILES}
