on:
  pull_request:
    branches:
      - 20220402_test
    paths:
      - dockerfiles/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: List Changefile
        id: changefile
        run: |
          echo ${GITHUB_TOKEN}
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/1/files"
          response=$(curl -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.v3+json" -s -X GET -G $URL)   		
          FILES=$(echo "${response}" | jq -r '.[] | .filename')
          set +e
          yaml_files=$(echo "${FILES}" | egrep '\.yaml$')
          json_files=$(echo "${FILES}" | egrep '\.json$')
          echo $json_files $yaml_files
