on:
  push:
    branches:
      - 20220402_test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: List Changefile
        id: changefile
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/1/files"
          response=$(curl -H 'authorization: Bearer ${{ secrets.TEST }}' -H "Accept: application/vnd.github.v3+json" -s -X GET -G $URL)   		
          echo ${response}
