name: build images test
on:
  pull_request:
    branches:
      - master
    paths:
      - dockerfiles/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: List Changefile
        id: changefile
        run: |
          echo ${GITHUB_TOKEN}
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          response=$(curl -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.v3+json" -s -X GET -G $URL)   		
          FILES=$(echo "${response}" | jq -r '.[] | .filename')
          json_files=$(echo "${FILES}" | egrep '\.json$')
          echo ${FILES}
          echo ${json_files}